###consul服务端口号
server:
  port: 82

spring:
  application:
    name: springcloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.2.110
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}

