server:
  port: 85

spring:
  application:
    name: springcloud-order-service
  #sleuth链路监控
  zipkin:
    base-url: http://192.168.2.110:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka