server:
  port: 8401

spring:
  application:
    name: spingcloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.110:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.2.110:8858 #配置Sentinel dashboard地址
        port: 8719
        clientIp: 192.168.2.103

      datasource: #<---------------------------关注点，添加Nacos数据源配置
        ds1:
          nacos:
            server-addr: 192.168.2.110:8848
            dataId: springcloud-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持


